authapp/urls.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from authapp.views import login, logout, RegisterUser, LoginUser

app_name = 'authapp'

urlpatterns = [
    path('register', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout, name='logout'),


    path('accounts/password_change/', PasswordChangeView.as_view(template_name='authapp/change_password.html', success_url='password_change_done'), name='password_change'),
    path('accounts/password_change/password_change_done/', PasswordChangeDoneView.as_view(template_name='authapp/password_changed.html'), name='password_change_done'),
    path('accounts/password_reset/', PasswordResetView.as_view(template_name='authapp/reset_password.html',
                                                               subject_template_name='authapp/reset_subject.txt',
                                                               email_template_name='authapp/reset_email.txt',
                                                               success_url='done'), name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(template_name='authapp/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='authapp/password_reset_confirm.html', success_url='reset_complete'), name='password_reset_confirm'),
    path('accounts/reset/Mg/set-password/reset_complete/', PasswordResetCompleteView.as_view(template_name='authapp/password_reset_complete.html'), name='reset_complete')
]

bboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.BbView.as_view(), name='index'),
    path('rubric/<slug:slug>/', views.BbByRubricView.as_view(), name='by_rubric'),
    path('add/', views.BbCreateView.as_view(), name='add_bb'),
    path('bbs/<slug:slug>/', views.BbDetailView.as_view(), name='bb_detail'),
    path('feedback/', views.FeedbackFormView.as_view(), name='feedback'),
    path('search/', views.Search.as_view(), name='search'),
    path('bbs/user/<slug:user_name>/', views.UsersBbs.as_view(), name='users_bbs'),
    path('bbs/delete/<int:pk>/', views.BbDelete.as_view(), name='bb_delete'),
    path('profile/<int:user_pk>/', views.PersonalProfile.as_view(), name='personal_profile'),
    path('send_message_for_bb/<int:receiver_id>/<int:bb_id>/', views.send_message_for_bb, name='send_message_for_bb'),
    path('messages/', views.Messages.as_view(), name='messages'),
]

eset/eset/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

firstsite/urls.py
from firstsite import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from bboard.views import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('tasksheet/', include('tasksheet.urls', namespace='tasksheet')),
    path('accounts/', include('allauth.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'bboard.views.page_not_found'

authapp/models.py
from django.db import models

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

authapp/views.py
import os
from datetime import datetime

from django.contrib import auth
from django.contrib.auth import authenticate, login

from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView

from authapp.forms import UserLoginForm, RegisterUserForm, LoginUserForm
from django.urls import reverse, reverse_lazy

from firstsite.settings import BASE_DIR


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'authapp/register.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'

        return context

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('index')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'authapp/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'

        return context

    def get_success_url(self):
        return reverse_lazy('index')


# def login(request):
#     title = 'Вход'
#     login_form = UserLoginForm(data=request.POST)
#
#     if request.method == 'POST' and login_form.is_valid():
#         username = request.POST['username']
#         password = request.POST['password']
#
#         user = authenticate(request, username=username, password=password)
#
#         if user is not None:
#             auth.login(request, user)
#             logg_path = os.path.join(BASE_DIR, 'logs', 'app.txt')
#             dt = datetime.now()
#
#             logs = f"Пользователь: {request.user}, " \
#                    f"Пароль: {request.POST['password']}, " \
#                    f"Method: {request.method}, " \
#                    f"DateTime: {dt}\n"
#
#             with open(logg_path, 'a', encoding='utf-8') as logg:
#                 logg.write(logs)
#
#             return HttpResponseRedirect(reverse('index'))
#
#         else:
#             return HttpResponse('ASD')
#
#     context = {
#         'title': title,
#         'login_form': login_form,
#     }
#
#     return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/authapp/change_password.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock title %}
{% block content %}

<div class="container">
    {% if not user.is_authenticated %}
        <p>Необходимо войти.</p>
    {% else %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button class="create-btn" type="submit">Изменить</button>
        <a href="{% url 'index' %}"><button class="create-btn" type="button">Отменить</button></a>
    </form>
</div>
{% endif %}

{% endblock %}

templates/authapp/login.html
{% extends "layout/basic.html" %}

{% block title %} {{ title }} {% endblock %}

{% block content %}

<div class="container">
    <h1 class="authapp-title">{{ title }}</h1>

    <div class="form-error"> {{ form.non_field_errors }} </div>

    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <p class="authapp-label"><label class="form-label-authapp" for="f.id_for_label">{{ f.label }}:</label> {{ f }} </p>
            <div class="form-error">
                {{ f.errors }}
            </div>
        {% endfor %}

            <button class="authapp-btn" type="submit">Войти</button>
            <a href="{% url 'authapp:password_reset' %}"><button type="button" class="authapp-btn">Сбросить пароль</button></a>

    </form>
</div>

{% endblock %}

templates/authapp/password_changed.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title%} {{ title }} {% endblock title %}
{% block content %}

<div class="container">
    <h1>Пароль успешно изменен.</h1>
</div>

{% endblock content %}

templates/authapp/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Пароль успешно сброшен</h1>
</body>
</html>

templates/authapp/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Изменить</button>
</form>
</body>
</html>

templates/authapp/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Отправилось!</p>
</body>
</html>

templates/authapp/register.html
{% extends "layout/basic.html" %}

{% block title %} {{ title }} {% endblock %}

{% block content %}

<div class="container">
    <h1 class="authapp-title">{{ title }}</h1>

    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <p class="authapp-label"><label class="form-label-authapp" for="f.id_for_label">{{ f.label }}:</label> {{ f }} </p>
            <div class="form-error">
                {{ f.errors }}
            </div>
        {% endfor %}

            <button class="authapp-btn" type="submit">Регистрация</button>

    </form>
</div>
{% endblock %}

templates/authapp/reset_password.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock title %}

{% block content %}
<div class="container">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="authapp-btn">Сбросить</button>
    </form>
</div>
{% endblock content %}